import json
import re

# Read current data
with open('D:/Project/ahmdd-zulfikar.github.io/kitab-kuning/fikih-manhaji/data.js', 'r', encoding='utf-8') as f:
    content = f.read()

json_str = content[content.find('['):content.rfind(';')]
data = json.loads(json_str)

# Define page 100 paragraphs
blocks_100 = []

def make_words(word_tuples):
    words = []
    for t in word_tuples:
        words.append({
            'text': t[0],
            'translation': t[1],
            'root': t[2],
            'explanation': t[3],
            'joined_explanation': t[4],
            'pronoun_ref': t[5],
            'irab': t[6],
            'verb_type': t[7],
            'fail_ref': t[8]
        })
    return words

# Para 1
p1_words = [
    ('لِلْإِنْسَانِ.', 'Bagi manusia.', 'أ ن س', '-', 'Lam jar + Al-Insan', '-', 'Jar Majrur', '-', '-'),
    ('فَكُلَّمَا', 'Maka setiap kali', 'ك ل ل', '-', 'Fa athaf + Kullama', '-', 'Huruf Syarat', '-', '-'),
    ('غَفَلَ', 'Lalai/Lupa', 'غ ف ل', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Al-Insan'),
    ('الْإِنْسَانُ', 'Manusia', 'أ ن س', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('وَاسْتَرْسَلَ', 'Dan hanyut/terlena', 'ر س ل', '-', 'Wawu athaf + Istarsala', '-', 'Fi\'il Madhi', 'Tsulasi Mazid', 'Al-Insan'),
    ('مَعَ', 'Bersama/Dengan', '-', '-', '-', '-', 'Zharf / Mudhaf', '-', '-'),
    ('الْوَسَائِطِ', 'Perantara', 'و س ط', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('الدُّنْيَوِيَّةِ', 'Duniawi', 'د ن و', '-', '-', '-', 'Na\'at', '-', '-'),
    ('الظَّاهِرَةِ،', 'Yang tampak,', 'ظ ه ر', '-', '-', '-', 'Na\'at', '-', '-'),
    ('جَاءَتِ', 'Datanglah', 'ج ي أ', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'As-Shalah'),
    ('الصَّلَاةُ', 'Shalat', 'ص ل ي', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('تُذَكِّرُهُ', 'Mengingatkannya', 'ذ ك ر', '-', 'Bersambung dhamir hu', 'hu merujuk ke Al-Insan', 'Fi\'il Mudhari\'', 'Tsulasi Mazid', 'As-Shalah'),
    ('بِأَنَّ', 'Bahwa sesungguhnya', '-', '-', 'Baa jar + Anna', '-', 'Jar Majrur', '-', '-'),
    ('الْمُسَبِّبَ', 'Sang Penyebab', 'س ب ب', 'Yang Maha Menentukan Sebab', '-', '-', 'Isim Anna', '-', '-'),
    ('هُوَ', 'Dialah', '-', '-', '-', 'Merujuk ke Allah', 'Dhamir Fashl', '-', '-'),
    ('اللهُ', 'Allah', '-', '-', '-', '-', 'Khabar Anna', '-', '-'),
    ('فَهُوَ', 'Maka Dia', '-', '-', 'Fa athaf + Dhamir Huwa', 'Merujuk ke Allah', 'Mubtada\'', '-', '-'),
    ('وَحْدَهُ', 'Sendiri-Nya', 'و ح د', '-', 'Bersambung dhamir hu', 'hu merujuk ke Allah', 'Hal / Manshub', '-', '-'),
    ('الْمُعِينُ', 'Sang Penolong', 'ع و ن', '-', '-', '-', 'Khabar', '-', '-'),
    ('وَالْمُنْعِمُ،', 'Dan Pemberi Nikmat,', 'ن ع م', '-', 'Wawu athaf + isim', '-', 'Ma\'thuf', '-', '-'),
    ('وَالضَّارُّ', 'Dan Pemberi Bahaya', 'ض ر ر', '-', 'Wawu athaf + isim', '-', 'Ma\'thuf', '-', '-'),
    ('وَالنَّافِعُ،', 'Dan Pemberi Manfaat,', 'ن ف ع', '-', 'Wawu athaf + isim', '-', 'Ma\'thuf', '-', '-'),
    ('وَالْمُحْيِي', 'Dan Yang Menghidupkan', 'ح ي ي', '-', 'Wawu athaf + isim', '-', 'Ma\'thuf', '-', '-'),
    ('وَالْمُمِيتُ.', 'Dan Yang Mematikan.', 'م و ت', '-', 'Wawu athaf + isim', '-', 'Ma\'thuf', '-', '-')
]
blocks_100.append({'type': 'paragraph', 'ar': 'لِلْإِنْسَانِ. فَكُلَّمَا غَفَلَ الْإِنْسَانُ وَاسْتَرْسَلَ مَعَ الْوَسَائِطِ الدُّنْيَوِيَّةِ الظَّاهِرَةِ، جَاءَتِ الصَّلَاةُ تُذَكِّرُهُ بِأَنَّ الْمُسَبِّبَ هُوَ اللهُ فَهُوَ وَحْدَهُ الْمُعِينُ وَالْمُنْعِمُ، وَالضَّارُّ وَالنَّافِعُ، وَالْمُحْيِي وَالْمُمِيتُ.', 'id': 'Bagi manusia. Maka setiap kali manusia lalai dan terlena dengan perantara-perantara duniawi yang tampak, shalat pun datang mengingatkannya bahwa Sang Penentu segala sebab adalah Allah, maka Dialah satu-satunya Sang Penolong dan Pemberi Nikmat, Pemberi Bahaya dan Pemberi Manfaat, serta Yang Menghidupkan dan Yang Mematikan.', 'words': make_words(p1_words)})

# Para 2
p2_words = [
    ('ثَالِثاً:', 'Ketiga:', 'ث ن ي', '-', '-', '-', 'Hal', '-', '-'),
    ('أَنْ', 'Agar', '-', '-', '-', '-', 'Huruf Mashdariyyah', '-', '-'),
    ('يَتَّخِذَ', 'Menjadikan', 'أ خ ذ', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mazid', 'Al-Insan'),
    ('الْإِنْسَانُ', 'Manusia', 'أ ن س', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('مِنْهَا', 'Darinya', '-', '-', 'Min + Dhamir ha', 'ha merujuk ke Shalat', 'Jar Majrur', '-', '-'),
    ('سَاعَةَ', 'Waktu/Saat', 'س و ع', '-', '-', '-', 'Maf\'ul Bih 1', '-', '-'),
    ('تَوْبَةٍ', 'Taubat', 'ت و ب', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('يَتُوبُ', 'Ia bertaubat', 'ت و ب', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mujarrad', 'Al-Insan'),
    ('فِيهَا', 'Di dalamnya', '-', '-', 'Fii + Dhamir ha', 'ha merujuk ke sa\'ah', 'Jar Majrur', '-', '-'),
    ('عَمَّا', 'Dari apa yang', '-', '-', 'An + Ma Maushul', '-', 'Jar Majrur', '-', '-'),
    ('يَكُونُ', 'Ia ada (terjadi)', 'ك و ن', '-', '-', '-', 'Fi\'il Mudhari\' Naqish', 'Tsulasi Mujarrad', 'Al-Insan'),
    ('قَدِ', 'Telah/Sungguh', '-', '-', '-', '-', 'Huruf Tahqiq', '-', '-'),
    ('اقْتَرَفَهُ', 'Ia melakukannya', 'ق ر ف', '-', 'Bersambung dhamir hu', 'hu merujuk ke ma', 'Fi\'il Madhi', 'Tsulasi Mazid', 'Al-Insan'),
    ('مِنَ', 'Dari', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('الْآثَامِ،', 'Dosa-dosa,', 'أ ث م', 'Jamak dari itsm', '-', '-', 'Majrur', '-', '-'),
    ('إِذِ', 'Karena/Tatkala', '-', '-', '-', '-', 'Zharf', '-', '-'),
    ('الْإِنْسَانُ', 'Manusia', 'أ ن س', '-', '-', '-', 'Mubtada\'', '-', '-'),
    ('مُعَرَّضٌ،', 'Diperhadapkan/Rentan,', 'ع ر ض', '-', '-', '-', 'Khabar', '-', '-'),
    ('فِي', 'Di/Dalam', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('سَاعَاتِ', 'Waktu-waktu', 'س و ع', '-', '-', '-', 'Majrur / Mudhaf', '-', '-'),
    ('يَوْمِهِ', 'Harinya', 'ي و م', '-', 'Bersambung dhamir hu', 'hu merujuk ke Al-Insan', 'Mudhaf Ilaih', '-', '-'),
    ('وَلَيْلِهِ،', 'Dan malamnya,', 'ل ي ل', '-', 'Wawu + isim + dhamir', 'hu merujuk ke Al-Insan', 'Ma\'thuf', '-', '-'),
    ('لِكَثِيرٍ', 'Bagi banyak (dosa)', 'ك ث ر', '-', 'Lam jar + Katsir', '-', 'Jar Majrur', '-', '-'),
    ('مِنَ', 'Dari', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('الْمَعَاصِي', 'Maksiat', 'ع ص ي', 'Jamak', '-', '-', 'Majrur', '-', '-'),
    ('الَّتِي', 'Yang', '-', '-', '-', '-', 'Na\'at / Isim Maushul', '-', '-'),
    ('قَدْ', 'Terkadang/Pernah', '-', '-', '-', '-', 'Huruf Taqil', '-', '-'),
    ('يَشْعُرُ', 'Ia menyadarinya', 'ش ع ر', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mujarrad', 'Al-Insan'),
    ('بِهَا', 'Dengannya (maksiat)', '-', '-', 'Baa + Dhamir ha', 'ha merujuk ke Ma\'ashi', 'Jar Majrur', '-', '-'),
    ('وَقَدْ', 'Dan terkadang', '-', '-', 'Wawu + Qad', '-', 'Huruf Athaf', '-', '-'),
    ('لَا', 'Tidak', '-', '-', '-', '-', 'Huruf Nafi', '-', '-'),
    ('يَشْعُرُ،', 'Menyadarinya,', 'ش ع ر', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mujarrad', 'Al-Insan'),
    ('فَتَكُونُ', 'Maka jadilah', 'ك و ن', '-', 'Fa + Takunu', '-', 'Fi\'il Mudhari\' Naqish', 'Tsulasi Mujarrad', 'Shalatu-hu'),
    ('صَلَاتُهُ', 'Shalatnya', 'ص ل ي', '-', 'Bersambung dhamir hu', 'hu merujuk ke Al-Insan', 'Isim Takunu', '-', '-'),
    ('الْمُتَكَرِّرَةُ', 'Yang berulang-ulang', 'ك ر ر', '-', '-', '-', 'Na\'at', '-', '-'),
    ('بَيْنَ', 'Di antara', '-', '-', '-', '-', 'Zharf', '-', '-'),
    ('الْحِينِ', 'Satu waktu', 'ح ي ن', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('وَالْآخَرِ', 'Dan waktu lainnya', 'أ خ ر', '-', 'Wawu + Al-Akhar', '-', 'Ma\'thuf', '-', '-'),
    ('تَطْهِيرًا', 'Sebagai penyucian', 'ط ه ر', '-', '-', '-', 'Khabar Takunu', '-', '-'),
    ('لَهُ', 'Baginya', '-', '-', 'Lam jar + hu', 'hu merujuk ke Al-Insan', 'Jar Majrur', '-', '-'),
    ('مِنْ', 'Dari', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('تِلْكَ', 'Itu (maksiat)', '-', '-', '-', '-', 'Isim Isyarah', '-', '-'),
    ('الْمَعَاصِي', 'Maksiat-maksiat', 'ع ص ي', '-', '-', '-', 'Badal', '-', '-'),
    ('وَالْأَوْزَارِ.', 'Dan dosa-dosa.', 'و ز ر', 'Jamak dari wizr', 'Wawu + Awzar', '-', 'Ma\'thuf', '-', '-'),
    ('وَقَدْ', 'Dan sungguh', '-', '-', '-', '-', 'Huruf Tahqiq', '-', '-'),
    ('أَوْضَحَ', 'Telah menjelaskan', 'و ض ح', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mazid', 'Rasulullah'),
    ('رَسُولُ', 'Rasul', 'ر س ل', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('اللهِ', 'Allah', '-', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('ﷺ', 'SAW', '-', '-', '-', '-', '-', '-', '-'),
    ('ذَلِكَ', 'Hal tersebut', '-', '-', '-', '-', 'Maf\'ul Bih', '-', '-'),
    ('فِي', 'Dalam', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('الْحَدِيثِ', 'Hadis', 'ح د ث', '-', '-', '-', 'Majrur', '-', '-'),
    ('الَّذِي', 'Yang', '-', '-', '-', '-', 'Na\'at / Isim Maushul', '-', '-'),
    ('رَوَاهُ', 'Diriwayatkannya', 'ر و ي', '-', 'Bersambung dhamir hu', 'hu merujuk ke Al-Hadits', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Muslim'),
    ('مُسْلِمٌ', 'Muslim', 'س ل م', 'Imam Muslim', '-', '-', 'Fa\'il', '-', '-'),
    ('(٦٦٨)،', '(668),', '-', '-', '-', '-', '-', '-', '-'),
    ('عَنْ', 'Dari', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('جَابِرِ', 'Jabir', '-', '-', '-', '-', 'Majrur', '-', '-'),
    ('بْنِ', 'Bin', 'ب ن ي', '-', '-', '-', 'Na\'at / Mudhaf', '-', '-'),
    ('عَبْدِ', 'Abdi', 'ع ب د', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('اللهِ', 'Allah', '-', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('رَضِيَ', 'Telah meridhai', 'ر ض ي', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Allah'),
    ('اللهُ', 'Allah', '-', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('عَنْهُ', 'Darinya', '-', '-', 'An + hu', 'hu merujuk ke Jabir', 'Jar Majrur', '-', '-'),
    ('قَالَ:', 'Beliau berkata:', 'ق و ل', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Jabir'),
    ('قَالَ', 'Telah bersabda', 'ق و ل', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Rasulullah'),
    ('رَسُولُ', 'Rasul', 'ر س ل', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('اللهِ', 'Allah', '-', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('ﷺ', 'SAW', '-', '-', '-', '-', '-', '-', '-'),
    (':', ':', '-', '-', '-', '-', '-', '-', '-'),
    ('«مَثَلُ', '«Perumpamaan', 'م ث ل', '-', '-', '-', 'Mubtada\'', '-', '-'),
    ('الصَّلَوَاتِ', 'Shalat-shalat', 'ص ل ي', 'Jamak', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('الْخَمْسِ', 'Lima (waktu)', 'خ م س', '-', '-', '-', 'Na\'at', '-', '-'),
    ('كَمَثَلِ', 'Seperti perumpamaan', 'م ث ل', '-', 'Kaf jar + matsal', '-', 'Jar Majrur / Khabar', '-', '-'),
    ('نَهَرٍ', 'Sungai', 'ن ه ر', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('جَارٍ', 'Yang mengalir', 'ج ر ي', '-', '-', '-', 'Na\'at', '-', '-'),
    ('غَمْرٍ', 'Yang airnya melimpah', 'غ م ر', '-', '-', '-', 'Na\'at 2', '-', '-'),
    ('عَلَى', 'Di', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('بَابِ', 'Pintu', 'ب و ب', '-', '-', '-', 'Majrur', '-', '-'),
    ('أَحَدِكُمْ،', 'Salah seorang kalian,', 'و ح د', '-', 'Ahad + kum', '-', 'Mudhaf Ilaih', '-', '-'),
    ('يَغْتَسِلُ', 'Ia mandi', 'غ س ل', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mazid', 'Ahad (seseorang)'),
    ('مِنْهُ', 'Darinya (sungai)', '-', '-', 'Min + hu', 'hu merujuk ke nahar', 'Jar Majrur', '-', '-'),
    ('كُلَّ', 'Setiap', 'ك ل ل', '-', '-', '-', 'Zharf Zaman', '-', '-'),
    ('يَوْمٍ', 'Hari', 'ي و م', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('خَمْسَ', 'Lima', 'خ م س', '-', '-', '-', 'Na\'ib Maf\'ul Muthlaq', '-', '-'),
    ('مَرَّاتٍ»', 'Kali»', 'م ر ر', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('قَالَ:', 'Berkata:', 'ق و ل', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Perawi'),
    ('قَالَ', 'Berkata', 'ق و ل', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Al-Hasan'),
    ('الْحَسَنُ:', 'Al-Hasan:', 'ح س ن', 'Hasan Al-Bashri', '-', '-', 'Fa\'il', '-', '-'),
    ('وَمَا', 'Dan apakah', '-', '-', 'Wawu + Ma Istifham', '-', 'Isim Istifham', '-', '-'),
    ('يُبْقِي', 'Akan menyisakan', 'ب ق ي', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mazid', 'Dzalika (hal itu)'),
    ('ذَلِكَ', 'Hal itu', '-', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('مِنَ', 'Dari', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('الدَّرَنِ؟.', 'Kotoran?.', 'د ر ن', '-', '-', '-', 'Majrur', '-', '-')
]
blocks_100.append({'type': 'paragraph', 'ar': 'ثَالِثاً: أَنْ يَتَّخِذَ الْإِنْسَانُ مِنْهَا سَاعَةَ تَوْبَةٍ يَتُوبُ فِيهَا عَمَّا يَكُونُ قَدِ اقْتَرَفَهُ مِنَ الْآثَامِ، إِذِ الْإِنْسَانُ مُعَرَّضٌ، فِي سَاعَاتِ يَوْمِهِ وَلَيْلِهِ، لِكَثِيرٍ مِنَ الْمَعَاصِي الَّتِي قَدْ يَشْعُرُ بِهَا وَقَدْ لَا يَشْعُرُ، فَتَكُونُ صَلَاتُهُ الْمُتَكَرِّرَةُ بَيْنَ الْحِينِ وَالْآخَرِ تَطْهِيرًا لَهُ مِنْ تِلْكَ الْمَعَاصِي وَالْأَوْزَارِ. وَقَدْ أَوْضَحَ رَسُولُ اللهِ ﷺ ذَلِكَ فِي الْحَدِيثِ الَّذِي رَوَاهُ مُسْلِمٌ (٦٦٨)، عَنْ جَابِرِ بْنِ عَبْدِ اللهِ رَضِيَ اللهُ عَنْهُ قَالَ: قَالَ رَسُولُ اللهِ ﷺ : «مَثَلُ الصَّلَوَاتِ الْخَمْسِ كَمَثَلِ نَهَرٍ جَارٍ غَمْرٍ عَلَى بَابِ أَحَدِكُمْ، يَغْتَسِلُ مِنْهُ كُلَّ يَوْمٍ خَمْسَ مَرَّاتٍ» قَالَ: قَالَ الْحَسَنُ: وَمَا يُبْقِي ذَلِكَ مِنَ الدَّرَنِ؟.', 'id': 'Ketiga: Agar manusia menjadikan shalat sebagai saat taubat yang di dalamnya ia memohon ampun dari dosa-dosa yang mungkin telah dilakukannya. Karena manusia sangat rentan dalam setiap jam siang dan malamnya terhadap banyak maksiat yang terkadang disadari atau tidak disadarinya, sehingga shalatnya yang berulang dari waktu ke waktu menjadi pembersih baginya dari maksiat dan dosa tersebut. Rasulullah SAW telah menjelaskan hal ini dalam sebuah hadits yang diriwayatkan oleh Muslim (668), dari Jabir bin Abdullah RA, ia berkata: Rasulullah SAW bersabda: "Perumpamaan shalat lima waktu itu ibarat sebuah sungai yang mengalir dan berair melimpah di depan pintu salah seorang dari kalian, yang darinya ia mandi setiap hari sebanyak lima kali." Perawi berkata: Al-Hasan (Al-Bashri) berkata: "Apakah hal itu masih menyisakan kotoran?"', 'words': make_words(p2_words)})

# Para 3 (Explanation Bracket)
p3_words = [
    ('[غَمْرٍ:', '[Ghamr:', 'غ م ر', '-', '-', '-', 'Khabar (mubtada mahdzuf)', '-', '-'),
    ('كَثِيرِ', 'Banyak', 'ك ث ر', '-', '-', '-', 'Na\'at / Khabar', '-', '-'),
    ('الْمِيَاهِ.', 'Air.', 'م و ه', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('الدَّرَنُ:', 'Ad-Daran:', 'د ر ن', '-', '-', '-', 'Mubtada\'', '-', '-'),
    ('الْوَسَخُ،', 'Kotoran,', 'و س خ', '-', '-', '-', 'Khabar', '-', '-'),
    ('وَالْمُرَادُ', 'Dan yang dimaksud', 'ر و د', '-', 'Wawu + Al-Murad', '-', 'Mubtada\'', '-', '-'),
    ('هُنَا', 'Di sini', '-', '-', '-', '-', 'Zharf', '-', '-'),
    ('الدَّرَنُ', 'Kotoran', 'د ر ن', '-', '-', '-', 'Khabar', '-', '-'),
    ('الْمَعْنَوِيُّ', 'Maknawi (non-fisik)', 'ع ن ي', '-', '-', '-', 'Na\'at', '-', '-'),
    ('وَهُوَ', 'Yaitu', '-', '-', 'Wawu + Huwa', 'Merujuk ke Daran Maknawi', 'Mubtada\'', '-', '-'),
    ('الذُّنُوبُ،', 'Dosa-dosa,', 'ذ ن ب', '-', '-', '-', 'Khabar', '-', '-'),
    ('وَيَدُلُّ', 'Dan menunjukkan', 'د ل ل', '-', 'Wawu + Yadullu', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mujarrad', 'Riwayatu'),
    ('عَلَى', 'Atas', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('ذَلِكَ', 'Hal itu', '-', '-', '-', '-', 'Majrur', '-', '-'),
    ('رِوَايَةُ', 'Riwayat', 'ر و ي', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('أَبِي', 'Abi', 'أ ب و', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('هُرَيْرَةَ', 'Hurairah', 'ه ر ر', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('رَضِيَ', 'Telah meridhai', 'ر ض ي', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mujarrad', 'Allah'),
    ('اللهُ', 'Allah', '-', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('عَنْهُ', 'Darinya', '-', '-', '-', 'Merujuk ke Abu Hurairah', 'Jar Majrur', '-', '-'),
    ('عِنْدَ', 'Di sisi (menurut)', 'ع ن د', '-', '-', '-', 'Zharf', '-', '-'),
    ('مُسْلِمٍ', 'Muslim', 'س ل م', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('أَيْضاً', 'Juga', 'أ ي ض', '-', '-', '-', 'Maf\'ul Muthlaq', '-', '-'),
    ('(٦٦٧):', '(667):', '-', '-', '-', '-', '-', '-', '-'),
    ('«فَذَلِكَ', '«Maka hal itu', '-', '-', 'Fa + Dzalika', '-', 'Mubtada\'', '-', '-'),
    ('مَثَلُ', 'Perumpamaan', 'م ث ل', '-', '-', '-', 'Khabar', '-', '-'),
    ('الصَّلَوَاتِ', 'Shalat', 'ص ل ي', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('الْخَمْسِ', 'Lima', 'خ م س', '-', '-', '-', 'Na\'at', '-', '-'),
    ('يَمْحُو', 'Menghapus', 'م ح و', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mujarrad', 'Allah'),
    ('اللَّهُ', 'Allah', '-', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('بِهِنَّ', 'Dengannya', '-', '-', 'Baa + hinna', 'hinna merujuk ke Shalawat Khams', 'Jar Majrur', '-', '-'),
    ('الْخَطَايَا»]', 'Kesalahan-kesalahan»]', 'خ ط أ', '-', '-', '-', 'Maf\'ul Bih', '-', '-')
]
blocks_100.append({'type': 'paragraph', 'ar': '[غَمْرٍ: كَثِيرِ الْمِيَاهِ. الدَّرَنُ: الْوَسَخُ، وَالْمُرَادُ هُنَا الدَّرَنُ الْمَعْنَوِيُّ وَهُوَ الذُّنُوبُ، وَيَدُلُّ عَلَى ذَلِكَ رِوَايَةُ أَبِي هُرَيْرَةَ رَضِيَ اللهُ عَنْهُ عِنْدَ مُسْلِمٍ أَيْضاً (٦٦٧): «فَذَلِكَ مَثَلُ الصَّلَوَاتِ الْخَمْسِ يَمْحُو اللَّهُ بِهِنَّ الْخَطَايَا»] .', 'id': '[Ghamr artinya: Air yang melimpah. Ad-Daran artinya: Kotoran, dan yang dimaksud di sini adalah kotoran maknawi yaitu dosa-dosa, dan hal ini ditunjukkan oleh riwayat dari Abu Hurairah RA di sisi Muslim juga (667): "Maka hal tersebut adalah perumpamaan shalat lima waktu, di mana Allah menghapuskan kesalahan-kesalahan dengannya."]', 'words': make_words(p3_words)})

# Para 4
p4_words = [
    ('رَابِعاً:', 'Keempat:', 'ر ب ع', '-', '-', '-', 'Hal', '-', '-'),
    ('أَنْ', 'Agar', '-', '-', '-', '-', 'Huruf Mashdariyyah', '-', '-'),
    ('تَكُونَ', 'Ia (shalat) menjadi', 'ك و ن', '-', '-', '-', 'Fi\'il Mudhari\' Naqish', 'Tsulasi Mujarrad', 'Shalat'),
    ('غِذَاءً', 'Nutrisi/Makanan', 'غ ذ و', '-', '-', '-', 'Khabar Takuna', '-', '-'),
    ('مُسْتَمِرًّا', 'Yang terus-menerus', 'م ر ر', '-', '-', '-', 'Na\'at', '-', '-'),
    ('لِعَقِيدَةِ', 'Bagi aqidah', 'ع ق د', '-', 'Lam jar + Aqidah', '-', 'Jar Majrur', '-', '-'),
    ('الْإِيمَانِ', 'Keimanan', 'أ م ن', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('بِاللهِ', 'Kepada Allah', '-', '-', 'Baa + Allah', '-', 'Jar Majrur', '-', '-'),
    ('تَعَالَى', 'Yang Maha Tinggi', 'ع ل و', '-', '-', '-', 'Fi\'il Madhi (Hal)', 'Tsulasi Mazid', 'Allah'),
    ('فِي', 'Dalam', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('قَلْبِهِ.', 'Hatinya.', 'ق ل ب', '-', 'Bersambung dhamir hi', 'hi merujuk ke Al-Insan', 'Majrur', '-', '-'),
    ('فَإِنَّ', 'Maka sesungguhnya', '-', '-', 'Fa + Inna', '-', 'Amil Nawasikh', '-', '-'),
    ('مُلْهِيَاتِ', 'Hal-hal yang melalaikan', 'ل ه و', '-', '-', '-', 'Isim Inna', '-', '-'),
    ('الدُّنْيَا', 'Dunia', 'د ن و', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('وَوَسَاوِسَ', 'Dan waswas/godaan', 'و س و س', '-', 'Wawu + Wasawis', '-', 'Ma\'thuf', '-', '-'),
    ('الشَّيْطَانِ', 'Setan', 'ش ط ن', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('مِنْ', 'Termasuk dari', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('شَأْنِهَا', 'Karakter/Sifatnya', 'ش أ ن', '-', 'Bersambung dhamir ha', 'ha merujuk ke Mulhiyat wa Wasawis', 'Majrur / Khabar Inna', '-', '-'),
    ('أَنْ', 'Untuk', '-', '-', '-', '-', 'Huruf Mashdariyyah', '-', '-'),
    ('تُنْسِيَ', 'Membuat lupa', 'ن س ي', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mazid', 'Mulhiyat wa Wasawis'),
    ('الْإِنْسَانَ', 'Manusia', 'أ ن س', '-', '-', '-', 'Maf\'ul Bih 1', '-', '-'),
    ('هَذِهِ', 'Ini', '-', '-', '-', '-', 'Isim Isyarah / Maf\'ul Bih 2', '-', '-'),
    ('الْعَقِيدَةَ', 'Aqidah', 'ع ق د', '-', '-', '-', 'Badal', '-', '-'),
    ('وَإِنْ', 'Sekalipun', '-', '-', 'Wawu + In', '-', 'Huruf Syarat', '-', '-'),
    ('كَانَتْ', 'Ia telah', 'ك و ن', '-', 'Bersambung ta\' ta\'nits', '-', 'Fi\'il Madhi Naqish', 'Tsulasi Mujarrad', 'Al-Aqidah'),
    ('مَغْرُوسَةً', 'Tertanam', 'غ ر س', '-', '-', '-', 'Khabar Kanat', '-', '-'),
    ('فِي', 'Di', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('قَلْبِهِ،', 'Dalam hatinya,', 'ق ل ب', '-', 'Bersambung dhamir hi', 'hi merujuk ke Al-Insan', 'Majrur', '-', '-'),
    ('فَإِذَا', 'Maka apabila', '-', '-', 'Fa + Idza', '-', 'Zharf Syarat', '-', '-'),
    ('اسْتَمَرَّ', 'Ia (manusia) terus-menerus', 'م ر ر', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mazid', 'Al-Insan'),
    ('فِي', 'Dalam', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('نِسْيَانِهِ', 'Kelupaannya', 'ن س ي', '-', 'Bersambung dhamir hi', 'hi merujuk ke Al-Insan', 'Majrur', '-', '-'),
    ('بِسَبَبِ', 'Disebabkan', 'س ب ب', '-', 'Baa + Sabab', '-', 'Jar Majrur', '-', '-'),
    ('انْصِرَافِهِ', 'Keberpalingannya', 'ص ر ف', '-', 'Bersambung dhamir hi', 'hi merujuk ke Al-Insan', 'Mudhaf Ilaih', '-', '-'),
    ('إِلَى', 'Kepada', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('ضَجِيجِ', 'Keriuhan', 'ض ج ج', '-', '-', '-', 'Majrur', '-', '-'),
    ('الْأَهْوَاءِ', 'Hawa nafsu', 'ه و ي', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('وَالشَّهَوَاتِ', 'Dan syahwat', 'ش ه و', '-', 'Wawu + Syahawat', '-', 'Ma\'thuf', '-', '-'),
    ('وَالْأَصْدِقَاءِ', 'Dan teman-teman (buruk)', 'ص د ق', '-', 'Wawu + Ashdiqa', '-', 'Ma\'thuf', '-', '-'),
    ('تَحَوَّلَ', 'Maka berubahlah', 'ح و ل', '-', '-', '-', 'Fi\'il Madhi (Jawab)', 'Tsulasi Mazid', 'An-Nisyan'),
    ('النِّسْيَانُ', 'Kelupaan itu', 'ن س ي', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('إِلَى', 'Menjadi', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('جُحُودٍ', 'Penentangan', 'ج ح د', '-', '-', '-', 'Majrur', '-', '-'),
    ('وَإِنْكَارٍ؛', 'Dan pengingkaran;', 'ن ك ر', '-', 'Wawu + Inkar', '-', 'Ma\'thuf', '-', '-'),
    ('كَالشَّجَرَةِ', 'Seperti pohon', 'ش ج ر', '-', 'Kaf jar + Syajarah', '-', 'Jar Majrur', '-', '-'),
    ('الَّتِي', 'Yang', '-', '-', '-', '-', 'Na\'at / Isim Maushul', '-', '-'),
    ('قُطِعَ', 'Terputus', 'ق ط ع', '-', '-', '-', 'Fi\'il Madhi Majhul', 'Tsulasi Mujarrad', 'Al-Ma\' (Air)'),
    ('عَنْهَا', 'Darinya', '-', '-', 'An + ha', 'ha merujuk ke Asy-Syajarah', 'Jar Majrur', '-', '-'),
    ('الْمَاءُ', 'Air', 'م و ه', '-', '-', '-', 'Na\'ib Fa\'il', '-', '-'),
    ('تَذْبُلُ', 'Ia layu', 'ذ ب ل', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mujarrad', 'Asy-Syajarah'),
    ('حِيناً', 'Beberapa saat', 'ح ي ن', '-', '-', '-', 'Zharf Zaman', '-', '-'),
    ('مِنَ', 'Dari', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('الزَّمَنِ', 'Waktu', 'ز م ن', '-', '-', '-', 'Majrur', '-', '-'),
    ('ثُمَّ', 'Kemudian', '-', '-', '-', '-', 'Huruf Athaf', '-', '-'),
    ('يَتَحَوَّلُ', 'Berubah', 'ح و ل', '-', '-', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mazid', 'Adz-Dzubul'),
    ('الذُّبُولُ', 'Kelayuan itu', 'ذ ب ل', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('إِلَى', 'Menjadi', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('مَوْتٍ', 'Kematian', 'م و ت', '-', '-', '-', 'Majrur', '-', '-'),
    ('وَتَتَحَوَّلُ', 'Dan berubah', 'ح و ل', '-', 'Wawu + Tatahawwalu', '-', 'Fi\'il Mudhari\'', 'Tsulasi Mazid', 'Asy-Syajarah'),
    ('الشَّجَرَةُ', 'Pohon itu', 'ش ج ر', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('إِلَى', 'Menjadi', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('حَطَبٍ', 'Kayu bakar', 'ح ط ب', '-', '-', '-', 'Majrur', '-', '-'),
    ('يَابِسٍ.', 'Yang kering.', 'ي ب س', '-', '-', '-', 'Na\'at', '-', '-'),
    ('وَلَكِنَّ', 'Akan tetapi', '-', '-', 'Wawu + Lakinna', '-', 'Amil Nawasikh', '-', '-'),
    ('الْمُسْلِمَ', 'Seorang muslim', 'س ل م', '-', '-', '-', 'Isim Lakinna', '-', '-'),
    ('إِذَا', 'Apabila', '-', '-', '-', '-', 'Zharf Syarat', '-', '-'),
    ('مَا', 'Sungguh', '-', '-', '-', '-', 'Huruf Zaidah', '-', '-'),
    ('ثَابَرَ', 'Ia tekun/menjaga', 'ث ب ر', '-', '-', '-', 'Fi\'il Madhi', 'Tsulasi Mazid', 'Al-Muslim'),
    ('عَلَى', 'Atas', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('الصَّلَاةِ،', 'Shalat,', 'ص ل ي', '-', '-', '-', 'Majrur', '-', '-'),
    ('كَانَتْ', 'Ia (shalat) menjadi', 'ك و ن', '-', 'Bersambung ta\' ta\'nits', '-', 'Fi\'il Madhi Naqish', 'Tsulasi Mujarrad', 'As-Shalah'),
    ('غِذَاءً', 'Nutrisi/Makanan', 'غ ذ و', '-', '-', '-', 'Khabar Kanat', '-', '-'),
    ('لِإِيمَانِهِ،', 'Bagi keimanannya,', 'أ م ن', '-', 'Lam jar + Iman + hi', 'hi merujuk ke Al-Muslim', 'Jar Majrur', '-', '-'),
    ('وَلَمْ', 'Dan tidak', '-', '-', 'Wawu + Lam', '-', 'Huruf Jazm', '-', '-'),
    ('تَعُدِ', 'Lagi', 'ع و د', '-', '-', '-', 'Fi\'il Mudhari\' Majzum', 'Tsulasi Mujarrad', 'Ad-Dunya'),
    ('الدُّنْيَا', 'Dunia', 'د ن و', '-', '-', '-', 'Fa\'il', '-', '-'),
    ('وَمُلْهِيَاتُهَا', 'Dan hal-hal yang melalaikannya', 'ل ه و', '-', 'Wawu + Mulhiyat + ha', 'ha merujuk ke Dunia', 'Ma\'thuf', '-', '-'),
    ('قَادِرَةً', 'Mampu', 'ق د ر', '-', '-', '-', 'Hal / Khabar Lam Ta\'ud', '-', '-'),
    ('عَلَى', 'Untuk', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('إِضْعَافِ', 'Melemahkan', 'ض ع ف', '-', '-', '-', 'Majrur', '-', '-'),
    ('الْإِيمَانِ', 'Iman', 'أ م ن', '-', '-', '-', 'Mudhaf Ilaih', '-', '-'),
    ('فِي', 'Dalam', '-', '-', '-', '-', 'Huruf Jar', '-', '-'),
    ('قَلْبِهِ', 'Hatinya', 'ق ل ب', '-', 'Bersambung dhamir hi', 'hi merujuk ke Al-Muslim', 'Majrur', '-', '-'),
    ('أَوْ', 'Atau', '-', '-', '-', '-', 'Huruf Athaf', '-', '-'),
    ('إِمَاتَتِهِ.', 'Mematikannya.', 'م و ت', '-', 'Bersambung dhamir hi', 'hi merujuk ke Al-Iman', 'Ma\'thuf', '-', '-')
]
blocks_100.append({'type': 'paragraph', 'ar': 'رَابِعاً: أَنْ تَكُونَ غِذَاءً مُسْتَمِرًّا لِعَقِيدَةِ الْإِيمَانِ بِاللهِ تَعَالَى فِي قَلْبِهِ. فَإِنَّ مُلْهِيَاتِ الدُّنْيَا وَوَسَاوِسَ الشَّيْطَانِ مِنْ شَأْنِهَا أَنْ تُنْسِيَ الْإِنْسَانَ هَذِهِ الْعَقِيدَةَ وَإِنْ كَانَتْ مَغْرُوسَةً فِي قَلْبِهِ، فَإِذَا اسْتَمَرَّ فِي نِسْيَانِهِ بِسَبَبِ انْصِرَافِهِ إِلَى ضَجِيجِ الْأَهْوَاءِ وَالشَّهَوَاتِ وَالْأَصْدِقَاءِ تَحَوَّلَ النِّسْيَانُ إِلَى جُحُودٍ وَإِنْكَارٍ؛ كَالشَّجَرَةِ الَّتِي قُطِعَ عَنْهَا الْمَاءُ تَذْبُلُ حِيناً مِنَ الزَّمَنِ ثُمَّ يَتَحَوَّلُ الذُّبُولُ إِلَى مَوْتٍ وَتَتَحَوَّلُ الشَّجَرَةُ إِلَى حَطَبٍ يَابِسٍ. وَلَكِنَّ الْمُسْلِمَ إِذَا مَا ثَابَرَ عَلَى الصَّلَاةِ، كَانَتْ غِذَاءً لِإِيمَانِهِ، وَلَمْ تَعُدِ الدُّنْيَا وَمُلْهِيَاتُهَا قَادِرَةً عَلَى إِضْعَافِ الْإِيمَانِ فِي قَلْبِهِ أَوْ إِمَاتَتِهِ.', 'id': 'Keempat: Agar shalat menjadi asupan gizi yang terus-menerus bagi aqidah keimanan kepada Allah Ta\'ala di dalam hatinya. Karena hal-hal yang melalaikan dari dunia dan godaan setan memiliki tabiat untuk membuat manusia melupakan aqidah ini meskipun telah tertanam di hatinya. Apabila ia terus-menerus dalam kelupaannya akibat berpaling pada keriuhan hawa nafsu, syahwat, dan teman-teman (yang buruk), maka kelupaan tersebut akan berubah menjadi penentangan dan pengingkaran; bagaikan pohon yang aliran airnya terputus, ia akan layu beberapa waktu kemudian kelayuan itu berubah menjadi kematian dan pohon itu pun menjadi kayu bakar yang kering. Akan tetapi, jika seorang muslim tekun mendirikan shalat, shalat tersebut akan menjadi gizi bagi keimanannya, sehingga dunia dan kelalaiannya tidak akan mampu lagi melemahkan atau mematikan iman di dalam hatinya.', 'words': make_words(p4_words)})

data.append({
    'pageNumber': 100,
    'blocks': blocks_100
})

js_content = 'const fikihData = ' + json.dumps(data, ensure_ascii=False, indent=4) + ';\n'
with open('D:/Project/ahmdd-zulfikar.github.io/kitab-kuning/fikih-manhaji/data.js', 'w', encoding='utf-8') as f:
    f.write(js_content)
print('Page 100 appended to data.js successfully.')
